version: '3'
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_APP_IMAGE_NAME=myflaskapp
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - mynetwork

networks:
  mynetwork:
